Documentation:
  - changed-files:
      - any-glob-to-any-file:
        - '**/*.md'

Github-files:
  - changed-files:
    - any-glob-to-any-file:
      - '.github/**'

Tests:
  - changed-files:
    - any-glob-to-any-file:
      - 'src/tests/**'

Papers:
  - changed-files:
    - any-glob-to-any-file:
      - 'papers/**'

Gradle:
  - changed-files:
    - any-glob-to-any-file:
      - 'build.gradle'
      - '**/build.gradle'
      - '**/gradle.properties'
      - '**/settings.gradle'
      - '**/gradlew'
      - '**/gradlew.bat'

Core:
  - changed-files:
    - any-glob-to-any-file:
      - 'src/main/java/**'
      - 'src/main/resources/**'
