name: Publish JAR file to release

on:
  workflow_dispatch:
    inputs:
      bump_type:
        type: choice
        required: true
        default: patch
        options:
          - patch
          - minor
          - major
        description: "Select the type of version bump for the release"
  #push:
  #  branches:
  #    - main

jobs:
  get_version:
    name: "Generate new release version"
    runs-on: ubuntu-latest
    outputs:
      v-version: ${{ steps.version.outputs.v-version }}
    steps:
      - name: Get next version
        uses: reecetech/version-increment@2026.8.4
        id: version
        with:
          release_branch: main
          use_api: true
          increment: ${{ github.event.inputs.bump_type || 'patch' }}

  upload_release:
    name: "Create Release and upload JAR file to Maven and GitHub"
    needs: [ get_version ]
    runs-on: ubuntu-latest
    steps:
      - name: Checkout project sources
        uses: actions/checkout@v7

      - name: Create JAR file
        uses: actions/setup-java@v6
        with:
          distribution: 'oracle'
          java-version: '21'
          cache: 'gradle'
      # Remove the leading v from the version string and set it as an environment variable
      - name: Set RELEASE_VERSION environment variable and create JAR file
        run: |
          VERSION=${{ needs.get_version.outputs.v-version }}
          VERSION=${VERSION#v}
          echo "VERSION=$VERSION" >> "$GITHUB_ENV"
          export VERSION
          ./gradlew publishToMavenLocal
        env:
          SIGNING_KEY: ${{ secrets.SIGNING_KEY }}

      # https://central.sonatype.org/publish/publish-portal-api/
      # https://central.sonatype.com/api-doc
      - name: Create Bundle.zip file and use Publisher API
        if: github.repository == 'ADWISE-VCU/Ciphercraft' && github.ref == 'refs/heads/main'
        run: |
          bash create_bundle.sh $VERSION
          curl --request POST \
            --verbose \
            --header "Authorization: Bearer ${BEARER_TOKEN}" \
            --form bundle=@bundle.zip \
            --form publishingType=AUTOMATIC \
            https://central.sonatype.com/api/v1/publisher/upload \
            --fail --write-out "%{http_code}" --output /dev/null
          if [ $? -ne 0 ]; then
            echo "Error: curl did not return 201. Failing the step."
            exit 1
          fi
        env:
          BEARER_TOKEN: ${{ secrets.BEARER_TOKEN }}
          SIGNING_KEY: ${{ secrets.SIGNING_KEY }}

      # You want to use the 'ciphercraft-<version>.jar' for your uses
      - name: Release the JAR file
        uses: softprops/action-gh-release@v3
        with:
          tag_name: ${{ needs.get_version.outputs.v-version }}
          files: build/libs/ciphercraft*.jar
          token: ${{ secrets.GITHUB_TOKEN }}
